### PR TITLE
In Progress: Mailing list

### LINKED ISSUE #33: Mailing list issues
* [ ] Need to fix CSS so the box and form are styled correctly
* [ ] Need to fix JS / CSS so text can actually be input onto the form
* [ ] Need to do a test-run to see that the form can actually be submitted correctly
* [ ] Need to add signup link to the mailing list from header

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #33. @Aaronontheweb started it off and we'll see if we can clean it up since he's on travel.

## Remaining Work
**To fix CSS so the box and form are styled correctly**

* [x] Yellow lines should become the green color we are using as an accent
* [x] Add Line at the bottom of the mailing list box
* [x] ~~Fix any awkward spacing prior to the footer~~ 
 * decided this isn't needed 
* [ ] Text of the form needs to match the size of the button
* [x] Button should likely share the accent color (sea foam green, not yellow)
* [ ] Bounding for the submit button

**Other Work**
* [x] Need to fix JS / CSS so text can actually be input onto the form
* [x] Need to do a test-run to see that the form can actually be submitted correctly
* [x] Need to add signup link to the mailing list from header

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@Aaronontheweb @RyKilleen welp -- I looked at it for a bit but I eclipsed my timebox and I'm dead for the week. Here's where I got stuck:

* No matter what the hell I did, I couldn't increase the padding of the e-mail text box higher than zero; I think something is overriding it somewhere and I can't figure out where. It's maddening.
* The text on the form wasn't being hidden or off the screen -- THE FONT WAS WHITE. :rage2: also, the style was being applied to `text` inputs, not `email` inputs. Fixed both of those.

**Comment by Aaronontheweb** [comment]
@SeanKilleen you guys are rockstars. this is probably good enough IMHO. No need to make perfect the enemy of good. Can always submit another PR with more fixes.

**Comment by Aaronontheweb** [comment]
Verified that the submit works.

**Comment by SeanKilleen** [comment]
@Aaronontheweb submit seemed to go to last year's list though (e.g. I got an error that I was already subscribed). Is that an issue?

**Comment by Aaronontheweb** [comment]
@SeanKilleen nope, it's the same list. Want to re-use it year after year

**Comment by Aaronontheweb** [comment]
Going to pipe this PR over to the main dotnetfringe repo so Troy and friends can deploy the site whenever they're ready. I'm sure we can fix that CSS issue on the go

**Comment by SeanKilleen** [comment]
@Aaronontheweb pipe the master branch over

**Pull request merged**
