### PR TITLE
Update docs to match new design

### PR DESCRIPTION
**Pull request by SeanKilleen**
This is where we'll ensure the style looks sane before redesigning the home page too.

To run, go to the `/docs` section (no link from the splash page currently).

When that link looks reasonably good, we'll be done.

### To Preview
* Pull this branch
* Run the site (follow directions in the readme, but basically run `bundle exec jekyll serve` from the root)
* Head to http://localhost:4000/docs

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@aaronontheweb / @RyKilleen FYI this is in progress but feel free to jump in on this branch and make any commits that you think would help. I kicked it off just to start it but I admittedly don't have the visual knack.

**Comment by Aaronontheweb** [comment]
got a preview we can look at? ;)

**Comment by Aaronontheweb** [comment]
cc @SeanKilleen

**Comment by SeanKilleen** [comment]
@Aaronontheweb easy preview:  pull this branch & run `bundle exec jekyll serve` and then head to `http://localhost:4000/docs`.

It, uhh....needs work still. Like, more than a little. But it's just CSS and at least it's all separated now.

**Comment by SeanKilleen** [comment]
@Aaronontheweb FYI haven't been able to touch it since late last night (client work all day). Anyone should feel free to pull the branch and make some improvements to keep it moving.

**Comment by RyKilleen** [comment]
@seankilleen I'll be chiming in a bunch tonight.

**Comment by RyKilleen** [comment]
@SeanKilleen The yellow link on blue background doesn't come close to passing color contrast. Do we have wiggle room for alternatives? Changing the background blue to a slightly darker blue would fix it for both text and link colors. (May I recommend #3a4787)

**Comment by SeanKilleen** [comment]
@rykilleen Yep! The original color scheme is grey and yellow -- it's half done now because I was in progress. Pull the master branch to see the original

**Comment by SeanKilleen** [comment]
💥

**Pull request merged**
